const feedstocks = [
  { label: 'Bedded Dairy', slug: 'bedded-dairy' },
  { label: 'Bedded Horse', slug: 'bedded-horse' },
  { label: 'Bedded Sheep', slug: 'bedded-sheep' },
  { label: 'Bedded Swine', slug: 'bedded-swine' },
  { label: 'Cattle Bedded', slug: 'cattle-bedded' },
  { label: 'Manure, Cattle', slug: 'manure-cattle' },
  { label: 'Manure, Dairy Cow', slug: 'manure-dairy-cow' },
  { label: 'Manure, Horse', slug: 'manure-horse' },
  { label: 'Manure, Poultry', slug: 'manure-poultry' },
  { label: 'Manure, Sheep', slug: 'manure-sheep' },
  { label: 'Manure, Swine', slug: 'manure-swine' },
  { label: 'Poultry Bedded', slug: 'poultry-bedded' },
  { label: 'Turkey Manure', slug: 'turkey-manure' },
  { label: 'Turkey Manure: Bedding', slug: 'turkey-manure:-bedding' },
  { label: 'Apple filter cake', slug: 'apple-filter-cake' },
  { label: 'Apple, Pomace', slug: 'apple-pomace' },
  { label: 'Apple, process sludge', slug: 'apple-process-sludge' },
  { label: 'Vegetable, produce', slug: 'vegetable-produce' },
  { label: 'Blood wastes', slug: 'blood-wastes' },
  { label: 'Crab and Lobster wastes', slug: 'crab-and-lobster-wastes' },
  { label: 'Fish, processing sludge', slug: 'fish-processing-sludge' },
  { label: 'Fish, wastes (gurry, racks, ect.)',slug: 'fish-wastes-gurry-racks-ect' },
  { label: 'Paunch manure', slug: 'paunch-manure' },
  { label: 'Shrimp Waste', slug: 'shrimp-waste' },
  { label: 'Activated Sludge', slug: 'activated-sludge' },
  { label: 'Digested sludge', slug: 'digested-sludge' },
  { label: 'Food Waste', slug: 'food-waste' },
  { label: 'Mixed food/green waste', slug: 'mixed-food-green-waste' },
  { label: 'Night soil', slug: 'night-soil' },
  { label: 'Paper from domestic use', slug: 'paper-from-domestic-use' },
  { label: 'Primary Sludge', slug: 'primary-sludge' },
  { label: 'Straw, general', slug: 'straw-general' },
  { label: 'Water', slug: 'water' },
  { label: 'Bark hardwoods', slug: 'bark-hardwoods' },
  { label: 'Bark softwoods', slug: 'bark-softwoods' },
  { label: 'Corrugated cardboard', slug: 'corrugated-cardboard' },
  { label: 'Dry Shavings', slug: 'dry-shavings' },
  { label: 'Newsprint', slug: 'newsprint' },
  { label: 'Paper OCC sludge', slug: 'paper-occ-sludge' },
  { label: 'Sawdust', slug: 'sawdust' },
  { label: 'Wood, hardwoods', slug: 'wood-hardwoods' },
  { label: 'Wood, softwoods', slug: 'wood-softwoods' },
  { label: 'Woodchips', slug: 'woodchips' },
  { label: 'Compacted and Moist', slug: 'compacted-and-moist' },
  { label: 'Compacted grass clippings', slug: 'compacted-grass-clippings' },
  { label: 'Grass Clippings', slug: 'grass-clippings' },
  { label: 'Leaves', slug: 'leaves' },
  { label: 'Loose dry leaves', slug: 'loose-dry-leaves' },
  { label: 'Loose Grass Clippings', slug: 'loose-grass-clippings' },
  { label: 'Seaweed', slug: 'seaweed' },
  { label: 'Shrub trimmings', slug: 'shrub-trimmings' },
  { label: 'Tree trimmings', slug: 'tree-trimmings' },
  { label: 'Water hyacinth', slug: 'water-hyacinth' },
];

export default feedstocks;
